dist: trusty
language: generic
sudo: required
install:
  - sudo .travis/install-alpine
  - sudo .travis/setup-alpine
script: |
  source .travis/common.sh
  alpine_run $USER .travis/build-pkgs
notifications:
  email: false
