sudo: required
dist: trusty
language: minimal
env:
  matrix:
    - ARCH=x86_64
    - ARCH=x86
    - ARCH=aarch64
    - ARCH=armhf
    - ARCH=ppc64le

before_install:
  - "wget 'https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/v0.5.1/alpine-chroot-install' \
        && echo '5414e27ceb85cefede5699ef2ec614f831cafd65  alpine-chroot-install' | sha1sum -c || exit 1"
  - alpine() { /alpine/enter-chroot -u "$USER" "$@"; }
install:
  - sudo sh alpine-chroot-install -a "$ARCH"
        -p 'build-base alpine-sdk libfetch-dev libressl libressl-dev linux-headers lua5.2-dev zlib-dev'
before_script:
  - /alpine/enter-chroot "addgroup $USER wheel && addgroup $USER abuild"
  - alpine abuild-keygen -ain
script:
  - alpine make
  - alpine src/apk --version
  - alpine make static
  - alpine src/apk.static --version
  - alpine make check
  - alpine make -C test root-tests

# If building a tagged commit, create and deploy tarball with statically linked
# apk to GitHub Releases.
before_deploy:
  - export PKGNAME="apk-tools-${TRAVIS_TAG#v}"
  - alpine strip src/apk.static
  - install -D -m 755 src/apk.static $PKGNAME/apk
  - tar -czf $PKGNAME-$ARCH-linux.tar.gz $PKGNAME
  - sha256sum $PKGNAME-$ARCH-linux.tar.gz > $PKGNAME-$ARCH-linux.tar.gz.sha256
deploy:
  provider: releases
  api_key:
    secure: "A8+gjM2ExMKnVfkF2LdXo7eQ2dJ8WgNPummEDwybKeu2vXHwur1zYSsKH0nr6+C3pyVFmiDT8Ho+KP8MMtKX0qLh1LeJtOSrwON9H36rNT2HrOPrASyp5+jGhtxHTe4CC/0F9aHLqOaDh2HU7qL3NqsUpJPxPDcvdEodFca0VfdeB/0S6FlnKVlg5zIdqENn9TRslzV5yvyqocvSqyXLtMamaIFtRe5GVZzOZdixStVKw6j/0EcK+ExaNgTDp9l1vJnQmToaqIWQMBT629nYrPSMC1DjJEeap3n8fLp1yPuak2yi2g64ne4mnk2CHU73YLj8c3yZzMyjzFC94WbTUTNpEwzeS2i5s9Ihm3JyeUED8dikPG1zmtdo9Fv8t+W9bg9rEXGa7K/HBdZjW998OAtJoL5toyNhL0tKDrRpgWKoxyt35L/eI/tj7wS5DudraW3pjabES8u5rXC27DBYAH/XO2V1pjg3ZCSF5HOyYAf6CctZ0fC2BMMaRmazzjIvniqAHfMeeyo85arReyrEAyFtD3xq5dEiRL3FfRByY49t3+2l96yKeLDl623Q0184iY2JOb9dW5H9n+QB6QlNndV/kPx6EcXXUOD/bpea91kayxVUfATYI3j2rxC94xnphURgZp9bcHETVrZgWae7EZDg/DGlQ690ztDJ3qQIGDU="
  file: apk-tools-*.tar.gz*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
