[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[log]
  level = "INFO"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
  [entryPoints.traefik]
  address = "localhost:8080"

[api]
  insecure = true
  dashboard = true

[pilot]
  dashboard = false

[ping]

#[certificatesResolvers.sample.acme]
#  email = ""
#  storage = "traefik/acme/account"
#  [certificatesResolvers.sample.acme.dnsChallenge]
#    provider = "cloudflare"
#    delayBeforeCheck = 10
