# Folder where your music library is stored. Can be read-only.
#MusicFolder = "music"

# Folder to store application data (DB, cache…)
#DataFolder = "."

# Folder to store cache data (transcoding, images…)
#CacheFolder = "cache"

# Log level. Useful for troubleshooting. Possible values: error, info, debug,
# trace.
#LogLevel = "info"

# IP address the server will bind to.
#Address = "0.0.0.0"

# Base URL (only the path part) to configure Navidrome behind a proxy
# (ex: /music)
#BaseUrl = ""

# HTTP port Navidrome will use.
#Port = 4533

# How many login requests can be processed from a single IP during the
# AuthWindowLength. Set to 0 to disable the limit rater.
#AuthRequestLimit = 5

# Window Length for the authentication rate limit.
#AuthWindowLength = "20s"

# Enable/disable .m3u playlist auto-import.
#AutoImportPlaylists = true

# Configure the order to look for cover art images. Use special embedded value
# to get embedded images from the audio files.
#CoverArtPriority = "cover.*, folder.*, front.*, embedded, external"

# Configure the order to look for artist images.
#ArtistArtPriority = "artist.*, album/artist.*, external"

# Set JPEG quality percentage for resized cover art images.
#CoverJpegQuality = 75

# Format to transcode to when client requests downsampling (specify
# maxBitrate without a format).
#DefaultDownsamplingFormat = "opus"

# Sets the default language used by the UI when logging in from a new browser.
# This value must match one of the file names in
# https://github.com/navidrome/navidrome/tree/master/resources/i18n. Ex: for
# Chinese Simplified it has to be zh-Hans (case sensitive).
#DefaultLanguage = "en"

# Sets the default theme used by the UI when logging in from a new browser.
# This value must match one of the options in the UI.
#DefaultTheme = "Dark"

# Enable image pre-caching of new added music.
#EnableArtworkPrecache = true

# Controls whether the player in the UI will animate the album cover (rotation).
#EnableCoverAnimation = true

# Enable the option in the UI to download music/albums/artists/playlists from
# the server.
#EnableDownloads = true

# Set this to false to completely disable ALL external integrations.
#EnableExternalServices = true

# Enable toggling "Heart"/"Loved" for songs/albums/artists in the UI (maps to
# "Star"/"Starred" in Subsonic Clients).
#EnableFavourites = true

# Use Gravatar images as the user profile image. Needs the user’s email to be
# filled.
#EnableGravatar = false

# Whether or not sensitive information (like tokens and passwords) should be
# redacted (hidden) in the logs.
#EnableLogRedacting = true

# If set to false, it will return the album CoverArt when a song CoverArt is
# requested.
#EnableMediaFileCoverArt = true

# Enable ReplayGain options in the UI.
#EnableReplayGain = true

# Enable the Sharing feature.
#EnableSharing=false

# Enable 5-star ratings in the UI.
#EnableStarRating = true

# Enables transcoding configuration in the UI.
#EnableTranscodingConfig = false

# Enable regular users to edit their details and change their password.
#EnableUserEditing = true

# Path to `ffmpeg` binary.
#FFmpegPath = ""

# Send basic info to your own Google Analytics account. Must be in the format
# UA-XXXXXXXX. Empty means disabled.
#GATrackingID = ""

# List of ignored articles when sorting/indexing artists.
#IgnoredArticles = "The El La Los Las Le Les Os As O A"

# Size of image (art work) cache. Set to 0 to disable cache.
#ImageCacheSize = "100MB"

# Maximum number of playlists shown in UI's sidebar.
#MaxSidebarPlaylists = 100

# Path to mpv executable. Used for Jukebox mode.
#MPVPath = ""

# Passphrase used to encrypt passwords in the DB. This is a one-time only
# configuration, and after this point the config option cannot be changed
# anymore or users won’t be able to authenticate.
#PasswordEncryptionKey = ""

# Where to search for and import playlists from. Can be a list of folders/globs
# (separated by : (or ; on Windows). Paths are relative to MusicFolder.
#PlaylistsPath = ".:**/**"

# Use Sort_* tags to sort columns in the UI.
#PreferSortTags = false

# Uses music files’ modification time when sorting by “Recently Added”.
# Otherwise use import time.
#RecentlyAddedByModTime = false

# HTTP header containing user name from authenticated proxy.
#ReverseProxyUserHeader = "Remote-User"

# Comma separated list of IP CIDRs which are allowed to use reverse proxy
# authentication, empty means “deny all”.
#ReverseProxyWhitelist = ""

# Configure periodic scans using “cron” syntax. To disable it altogether, set
# it to "" (empty string).
#ScanSchedule = "@every 1m"

# Match query strings anywhere in searchable fields, not only in word
# boundaries. Useful for languages where words are not space separated.
#SearchFullString = false

# How long Navidrome will wait before closing web ui idle sessions.
#SessionTimeout = "24h"

# When requesting artist’s albums, include albums where the artist participates
# (ex: Various Artists compilations).
#SubsonicArtistParticipations = false

# Path for the TLS certificate file.
#TLSCert = ""

# Path for the TLS key file.
#TLSKey = ""

# Size of transcoding cache. Set to 0 to disable cache.
#TranscodingCacheSize = "100MB"

# Change background image used in the Login page.
#UILoginBackgroundUrl = "https://source.unsplash.com/random/1600x900?music"

# Add a welcome message to the login screen.
#UIWelcomeMessage = ""

# Set file permissions for Unix Socket File.
#UnixSocketPerm = "0660"

# Change how album play count is computed. When set to "normalized", album play count will be divided by the number of album tracks
#AlbumPlayCountMode = "absolute"

# Cmd template used to construct the call of the mpv executable. Used for Jukebox mode
#MPVCmdTemplate = "mpv --audio-device=%d --no-audio-display --pause %f --input-ipc-server=%s"

# Allows the X-Frame-Options header value to be set with a custom value. Ex: "SAMEORIGIN"
#HTTPSecurityHeaders.CustomFrameOptionsValue = "DENY"

# [Jukebox]
# Enable Jukebox mode (play audio on server’s hardware).
#Enabled = false

# List of devices that can be used by the Jukebox.
#Devices = []

# Device to use for Jukebox mode, if there are multiple Jukebox.Devices entries.
#Default = ""

# [LastFM]
# Last.FM ApiKey.
#ApiKey = ""

# Set this to false to completely disable Last.FM integration.
#Enabled = true

# Two letter-code for language to be used to retrieve biographies from Last.FM
#Language = "en"

# Last.FM Shared Secret.
#Secret = ""

# [ListenBrainz]
# Set this to override the default ListenBrainz base URL.
#BaseUrl = "https://api.listenbrainz.org/1/"

# Set this to false to completely disable ListenBrainz integration.
#Enabled = true

# [Prometheus]
# Enable extra endpoint with Prometheus metrics.
#Enabled = false

# Custom path for Prometheus metrics. Useful for blocking unauthorized metrics
# requests.
#MetricsPath = "/metrics"

# [Scanner]
# Select metadata extractor implementation. Options: taglib or ffmpeg.
#Extractor = "taglib"

# List of separators to split genre tags.
#GenreSeparator = ";/,"

# “true” groups albums with the same Artist + Album Title as one album; “false”
# splits re-issues (=different Release Date) into separate albums.
#GroupAlbumReleases = false

# [Spotify]
# Spotify Client ID.
#ID = ""

# Spotify Client Secret.
#Secret = ""
