# Dertain packages require a lot of resources
- conditions:
    changed_aports:
      - chromium
  job_conditions:
    - has_tag: x86_64
  actions:
    add_tags: [ci-large]

# Larger rebuilds
- conditions:
    nr_changes: 5
  job_conditions:
    - has_tag: x86_64
  actions:
    add_tags: [ci-large]
