# Certain packages require a lot of resources
- conditions:
    changed_aports:
      - chromium
      - rio
      - nodejs
      - nodejs-current
      - qt6-qtwebengine
  job_conditions:
    - has_tag: x86_64
    - has_tag: aarch64
  actions:
    add_tags: [ci-large]

# Larger rebuilds
- conditions:
    nr_changes: 5
  job_conditions:
    - has_tag: x86_64
    - has_tag: aarch64
  actions:
    add_tags: [ci-large]
