# browser is the shell (/bin/sh) command executed once the proxy starts.
# When browser exits, the proxy exits. An extra env var PROXY is available.
#
# Here, we use a separate Chromium instance in Incognito mode, so that
# it can run (and be waited for) alongside the default one, and that
# it maintains no state across runs. To configure this browser open a
# normal window in it, settings will be preserved.
browser = """
    chromium \
    --user-data-dir="$HOME/.google-chrome-captive" \
    --proxy-server="socks5://$PROXY" \
    --no-first-run \
    --new-window \
    --incognito \
    --no-default-browser-check \
    --no-crash-upload \
    --disable-extensions \
    --disable-sync \
    --disable-background-networking \
    --disable-client-side-phishing-detection \
    --disable-component-update \
    --disable-translate \
    --disable-web-resources \
    --safebrowsing-disable-auto-update \
    http://example.com
"""

# dhcp-dns is the shell (/bin/sh) command executed to obtain the DHCP
# DNS server address. The first match of an IPv4 regex is used.
# IPv4 only, because let's be real, it's a captive portal.
#
# When using BusyBox udhcpc on Alpine Linux, it is recommended to
# configure udhcpc to create an /etc/resolv.conf.dhcp file. This
# can be achieved using the following /etc/udhcpc/udhcpc.conf entry:
#
#  RESOLV_CONF="/etc/resolv.conf.dhcp"
#
# The following command extracts the nameservers from that file.
dhcp-dns = "awk '/^nameserver / { print $2 }' /etc/resolv.conf.dhcp"

# socks5-addr is the listen address for the SOCKS5 proxy server.
socks5-addr = "localhost:1666"

# bind-device is the interface over which outbound connections (both HTTP
# and DNS) will be established. It can be used to avoid address space collisions
# but it requires CAP_NET_RAW or root privileges. Disabled by default.
#bind-device = "wlan0"
